---
# connector deployment

- name: deploys the application
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  tasks:
  - name: Create a new instance
    os_server:
       state: present
       auth:
         auth_url: http://192.168.0.140:35357/v3
         username: demo
         password: demo
         project_name: demo
         domain_name: default
       name: "{{app_name}}_{{ app_env }}"
       availability_zone: LXD
       image: 17e810a0-672c-42ba-a719-0ecdf26020ab
       key_name: pradeep
       security_groups: default
       timeout: 200
       flavor: 56a36b22-cc3d-421e-b54b-29b33525fad3
       meta:
         hostname: "{{app_name}}_{{ app_env }}"
       userdata: |
          {%- raw -%}#!/bin/bash
          apt-get update && sudo apt-get upgrade
          apt-get install -y python
          apt-get install -y default-jre
          {% endraw %}
    register: newnodes
