---
# connector deployment

- name: deploys the application
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  tasks:
  - name: Create a new instance
    os_server:
       state: present
       auth:
         auth_url: http://192.168.0.140:35357/v3
         username: demo
         password: demo
         project_name: demo
         domain_name: default
       name: "{{app_name}}_{{ app_env }}"
       availability_zone: LXD
       image: f274c084-0a90-43d0-a288-dd15d33bb523
       key_name: pradeep
       security_groups: default
       timeout: 200
       flavor: 56a36b22-cc3d-421e-b54b-29b33525fad3
       meta:
         hostname: "{{app_name}}_{{ app_env }}"
    register: newnodes
