---
# connector deployment

- name: deploys the application
  hosts: all
  vars:
    timestamp: ""

  tasks:
    - name: create the app directory
      file: path=/home/cloud-user/petclinic state=directory
      
    - name: copies the startup script
      copy: src=start-app.sh dest=/home/cloud-user/petclinic
      
    - name: copies the stop script
      copy: src=stop-app.sh dest=/home/cloud-user/petclinic
      
    - name: copies the jar file over
      copy: src=../target/app.jar dest=/home/cloud-user/petclinic/app-.jar

    - name: unlink the current app
      file: path=/home/cloud-user/petclinic/app.jar state=absent

    - name: link to the newly deployed app
      file: path=/home/cloud-user/petclinic/app.jar src=/home/cloud-user/petclinic/app-.jar state=link

    - name: stops running app
      command: /bin/sh /home/cloud-user/petclinic/stop-app.sh
      args:
        chdir: /home/cloud-user/petclinic/

    - name: starts the app
      shell: /bin/sh /home/cloud-user/petclinic/start-app.sh
      args:
        chdir: /home/cloud-user/petclinic/
        
    - name: Send notification message via Slack
      slack:
        token: xoxp-2179080664-169321284001-192831611058-04818f00e04313642c798e01ec733859
         msg: petclinic-integration deployment completed: <http://192.168.0.210:8080/view/petclinic-project/job/petclinic_integration_deployment|jenkins>!
         channel: #devops-cloud-demo
         username: 'Ansible'
      delegate_to: localhost
